### ISSUE TITLE
Can you provide degrade-audio-safe-random.py file in channel_simulation/simulated_compression.py

### ISSUE THREAD

**Issue by ganggang233** [yzyouzhang/ASVspoof2021_AIR#18]
The file I found in the repo you provide is not work

**Comment by ganggang233** [comment]
> The file I found in the repo you provide is not work

Looking forward to your reply

**Comment by yzyouzhang** [comment]
Thanks for the question. Please first make sure you have installed the repo for simulating channel effects. https://github.com/idiap/acoustic-simulator
The `degrade-audio-safe-random.py` file is in their repo and you need to put my `simulated_compression.py` file in the folder of the acoustic simulator.

**Comment by ganggang233** [comment]
> Thanks for the question. Please first make sure you have installed the repo for simulating channel effects. https://github.com/idiap/acoustic-simulator The `degrade-audio-safe-random.py` file is in their repo and you need to put my `simulated_compression.py` file in the folder of the acoustic simulator.

Thanks a lot, i will try.
