### ISSUE TITLE
Detailed performance of DF submission on different channels and attacks.

### ISSUE THREAD

**Issue by Betciso** [yzyouzhang/ASVspoof2021_AIR#19]
Sir, I have read your article.And i have some questions.i can't understand this Figure 4.How did you get this figure4.The test set has no tags,so how did you know which spoofing attack method was used?

**Comment by yzyouzhang** [comment]
Thank you for your question and your interest in our paper. 
The meta labels for the ASVspoof 2021 dataset are not released yet. The numbers in Figures 4&6 and Tables 3-5 are all provided by the organizers. When we submitted our scores for the challenge, the organizers sent back these detailed results to us. I believe they have some backends to produce such results.
Please let me know if you have further questions. Thanks.

**Comment by Betciso** [comment]
Thanks for your answer.I get it .

**Comment by yzyouzhang** [comment]
If you would like to study the effect of channel variation with meta labels, you can refer to our previous Interspeech paper https://github.com/yzyouzhang/Empirical-Channel-CM. We also released the augmented dataset https://zenodo.org/record/5794671.
