### ISSUE TITLE
运行出问题

### ISSUE THREAD

**Issue by beijita-yegucheng** [yzyouzhang/ASVspoof2021_AIR#21]
applying irspace
  space IR ({'filter': 'NiceDrumRoom-16000.ir', 'wet': 100}) 
  only 1 file matching .*NiceDrumRoom-16000.ir.*
  using /root/data/acoustic-simulator-master/impulse-responses/spaces/small/voxengo/NiceDrumRoom-16000.ir
/root/data/acoustic-simulator-master/src/sox-14.4.2/src/sox FAIL fir: couldn't open file /root/data/acoustic-simulator-master/impulse-responses/spaces/small/voxengo/NiceDrumRoom-16000.ir: No such file or directory
/root/data/acoustic-simulator-master/src/sox-14.4.2/src/sox FAIL formats: can't open input file `tmp/C4OFRTBBD97N893/LA_T_1000137-1-tmp3-irspace.raw': No such file or directory
Traceback (most recent call last):
  File "./degrade-audio-safe-random.py", line 960, in <module>
    rmsPostFIR=getSpeechRMSAmp(fileOutTmp3Raw, '-t raw -e signed-integer -b 16 -r ' + str(fileInRate))
  File "./degrade-audio-safe-random.py", line 682, in getSpeechRMSAmp
    if os.path.getsize(tmp)>0:
  File "/usr/lib64/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: 'tmp/C4OFRTBBD97N893/LA_T_1000137-1-tmp3-irspace.raw-getSpeechRMSAmp.raw'
read 15 space impulse reponses
当我运行， simulated_device.py这个代码的时候，总是报这个错，但是运行 simulated_channel.py就没有问题，我应该如何解决这个问题。

**Comment by yzyouzhang** [comment]
可以再检查一下你们IR的安装 要照着这个repo的来
https://github.com/idiap/acoustic-simulator/blob/master/README-impulse-responses.txt

**Comment by beijita-yegucheng** [comment]
十分谢谢，您的回复

**Comment by beijita-yegucheng** [comment]
applying norm
  normalizing audio ({'rms': '-26'})
  applying gain 0.44 to match -26dbFS RMS power

applying aac
  encoding AAC {'bit-rate': '32k'}
  decoding AAC {'bit-rate': '32k'}
cp: cannot stat 'tmp/JRIQ37WEDICB27T/LA_T_1000137-1-codec-norm-2-tmp4-aac.raw': No such file or directory

resampling to 16ksps
/home/huge/Desktop/ASVspoof/acoustic-simulator/src/sox-14.4.2/src/sox FAIL formats: can't open input file `tmp/JRIQ37WEDICB27T/LA_T_1000137-1-codec-norm-2-codec-aac.raw': No such file or directory
不好意思，又打扰您了，当我最近运行python simulated_compression.py 时候，老是出现这个错误，我已经按照https://github.com/idiap/acoustic-simulator/blob/master/README-codecs.txt这里，将现在还能装的都装了，可是这个问题还一直存在。

**Comment by yzyouzhang** [comment]
可以检查一下您tmp/JRIQ37WEDICB27T/LA_T_1000137-1-codec-norm-2-codec-aac.raw这个文件是否存在，也可能你安装在了另一个路径下，改一下默认路径就可以了

**Comment by beijita-yegucheng** [comment]
我又重新安装了一下sox与ffmpeg等，但是还是出现这个错，问题是程序不会生成这个目录tmp/JRIQ37WEDICB27T/，所以后续的操作不通，当我单独运行degrade-audio-safe-random.py 时候，会出现这个错Traceback (most recent call last):
&nbsp; File "degrade-audio-safe-random.py", line 802, in <module&gt;
&nbsp; &nbsp; fext = os.path.splitext (fileIn)[1]
&nbsp; File "/usr/lib/python2.7/posixpath.py", line 98, in splitext
&nbsp; &nbsp; return genericpath._splitext(p, sep, altsep, extsep)
&nbsp; File "/usr/lib/python2.7/genericpath.py", line 99, in _splitext
&nbsp; &nbsp; sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yzyouzhang/ASVspoof2021_AIR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 凌晨5:03
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [yzyouzhang/ASVspoof2021_AIR] 运行出问题 (Issue #21)





 
可以检查一下您tmp/JRIQ37WEDICB27T/LA_T_1000137-1-codec-norm-2-codec-aac.raw这个文件是否存在，也可能你安装在了另一个路径下，改一下默认路径就可以了

**Comment by gzhu06** [comment]
请问能打印下这个fileIn嘛？

**Comment by yzyouzhang** [comment]
> 我又重新安装了一下sox与ffmpeg等，但是还是出现这个错，问题是程序不会生成这个目录tmp/JRIQ37WEDICB27T/，所以后续的操作不通，当我单独运行degrade-audio-safe-random.py 时候，会出现这个错Traceback (most recent call last): &nbsp; File "degrade-audio-safe-random.py", line 802, in <module&gt; &nbsp; &nbsp; fext = os.path.splitext (fileIn)[1] &nbsp; File "/usr/lib/python2.7/posixpath.py", line 98, in splitext &nbsp; &nbsp; return genericpath._splitext(p, sep, altsep, extsep) &nbsp; File "/usr/lib/python2.7/genericpath.py", line 99, in _splitext &nbsp; &nbsp; sepIndex = p.rfind(sep) AttributeError: 'NoneType' object has no attribute 'rfind'
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yzyouzhang/ASVspoof2021_AIR" ***@***.***&gt;; 发送时间:&nbsp;2022年4月14日(星期四) 凌晨5:03 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [yzyouzhang/ASVspoof2021_AIR] 运行出问题 (Issue #21) 可以检查一下您tmp/JRIQ37WEDICB27T/LA_T_1000137-1-codec-norm-2-codec-aac.raw这个文件是否存在，也可能你安装在了另一个路径下，改一下默认路径就可以了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

请问这个问题解决了吗？

**Comment by beijita-yegucheng** [comment]
没有



---原始邮件---
发件人: "You ***@***.***&gt;
发送时间: 2022年5月3日(周二) 中午1:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [yzyouzhang/ASVspoof2021_AIR] 运行出问题 (Issue #21)




  
我又重新安装了一下sox与ffmpeg等，但是还是出现这个错，问题是程序不会生成这个目录tmp/JRIQ37WEDICB27T/，所以后续的操作不通，当我单独运行degrade-audio-safe-random.py 时候，会出现这个错Traceback (most recent call last): &nbsp; File "degrade-audio-safe-random.py", line 802, in <module&gt; &nbsp; &nbsp; fext = os.path.splitext (fileIn)[1] &nbsp; File "/usr/lib/python2.7/posixpath.py", line 98, in splitext &nbsp; &nbsp; return genericpath._splitext(p, sep, altsep, extsep) &nbsp; File "/usr/lib/python2.7/genericpath.py", line 99, in _splitext &nbsp; &nbsp; sepIndex = p.rfind(sep) AttributeError: 'NoneType' object has no attribute 'rfind'
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yzyouzhang/ASVspoof2021_AIR" @.&gt;; 发送时间:&nbsp;2022年4月14日(星期四) 凌晨5:03 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [yzyouzhang/ASVspoof2021_AIR] 运行出问题 (Issue #21) 可以检查一下您tmp/JRIQ37WEDICB27T/LA_T_1000137-1-codec-norm-2-codec-aac.raw这个文件是否存在，也可能你安装在了另一个路径下，改一下默认路径就可以了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
请问这个问题解决了吗？

**Comment by yzyouzhang** [comment]
> 没有

请问能打印下这个fileIn嘛？
