### ISSUE TITLE
hello, how can i get EER or min-tDCF of different codec (C1-C7)， the label did not provide this information

### ISSUE THREAD

**Issue by alexw914** [yzyouzhang/ASVspoof2021_AIR#24]

**Comment by yzyouzhang** [comment]
Thank you for your question. The organisers provided us the results of different channels by running their scripts on our score files, when we participated the challenge. It is true that they have not released the meta labels yet.

**Comment by alexw914** [comment]
Thanks， i asked the organizers， they provide a new challenge on codalab.

**Comment by alexw914** [comment]
LA: https://competitions.codalab.org/competitions/35161
PA: https://competitions.codalab.org/competitions/35160
DF: https://competitions.codalab.org/competitions/35159
