### ISSUE TITLE
你好对这个项目非常感兴趣，这个项目也可以做PA的任务吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [yzyouzhang/ASVspoof2021_AIR#27]
你好
       我看你的论文上介绍的是LA 和DF的任务，但是看代码里面有包含PA的部分，所以比较迷惑，我能使用[ASVspoof2019 PA的数据集 训练一个检测relay attack 模型吗？谢谢！

**Comment by yzyouzhang** [comment]
可以的，但我们没有做相关实验，我们的论文主要解决的是LA的泛化性问题。你感兴趣的话可以在PA上尝试，谢谢！

**Comment by zuowanbushiwo** [comment]
你好
     非常您的感谢快速回复，可以使用你们的工程训练一个可以检测PA,LA和DF的模型吗？我看了几篇文章和项目都是分开训练的，是因为这几个任务所需要的特征不一样吗？问题比较小白，我是刚入门ASVspoof，前段时间刚训练一个声纹的模型，昨天才开始看antispoof，ASVspoof的资料。谢谢！

**Comment by yzyouzhang** [comment]
LA和DF特征是一样的 都是检测算法的artifacts，PA是检测device的artifacts，建议先从ASVspoof 2019的比赛资料开始看，ASVspoof 2021的增加了codec的影响

**Comment by yzyouzhang** [comment]
LA PA放在一起训练是一个很好的研究课题，目前我所知还没有关于这方面的进展

**Comment by zuowanbushiwo** [comment]
好的，感谢大佬指点。

**Comment by zuowanbushiwo** [comment]
@yzyouzhang 
大佬还请教一个问题，我看了ASVspoof 2019 结果 如下：
![image](https://user-images.githubusercontent.com/3354428/217412804-93a20916-73f4-4fe5-a273-e0f278412a3f.png)
这个T05 团队的论文没有找到，我只搜索到 ID R&D 这个[公司 ](https://www.idrnd.ai/id-rd-ranks-first-in-detecting-synthetic-speech-in-global-asvspoof-challenge/)，这个得分太高了，比第二名都高很多。这个模型应该很大吧，我看介绍是7个特征和7个模型组合而成的。
![image](https://user-images.githubusercontent.com/3354428/217413754-0643705a-91fd-4af2-a275-0d27c2620c7f.png)
![image](https://user-images.githubusercontent.com/3354428/217414223-e8bcf5de-7561-4c3b-87b0-78ebeee7376a.png)

**Comment by yzyouzhang** [comment]
是的 他们当时没有发论文，最新的SASV的比赛中他们也是第一，他们的风格就是又大又强
https://sasv-challenge.github.io/pdfs/2022_descriptions/IDVoice.pdf

**Comment by zuowanbushiwo** [comment]
好的，了解了，我还以为是我没找到了，真的太强了，2019年的成果，现在都还没有人比他们高。不像其他的比赛，去年的第一名，今年都有可能排不上号了。是不是LA的任务比PA的难度要高很多？LA的文章要多很多，而且LA 任务的EER 整体比PA要高很多。

**Comment by yzyouzhang** [comment]
他们用的是7个子系统的fusion，现在research的话一般比的是single system

LA的任务和PA的关注点不一样 很难说哪个更难，如果从2021的比赛来看的话PA的EER要高很多，原因是2019的PA数据是simulated 而2021PA的eval data是真实录的

**Comment by zuowanbushiwo** [comment]
好的，感谢大佬回复，对于初学者来说，从你这里获得了很多信息。祝您身体健康，科研顺利！

**Comment by yzyouzhang** [comment]
谢谢！也祝你科研顺利！有问题可以继续在这留言或者email我: you.zhang@rochester.edu
